export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_ERROR";
export const LOGOUT = "SIGNOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const ADD_COMMENTS = "ADD_COMMENTS";
